/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _aibo204_dsh_plugin_computer_use_computerUseArchive_cleanup_result$schema = z.object({
  'deleted': z.number().readonly(),
  'bytesFreed': z.number().readonly(),
  'remainingBytes': z.number().readonly(),
})
const _aibo204_dsh_plugin_computer_use_computerUseArchive_delete_parameter_0$schema = z.string()
const _aibo204_dsh_plugin_computer_use_computerUseArchive_delete_result$schema = z.void()
const _aibo204_dsh_plugin_computer_use_computerUseArchive_image_parameter_0$schema = z.string()
const _aibo204_dsh_plugin_computer_use_computerUseArchive_image_parameter_1$schema = z.union([z.literal("before"), z.literal("after")])
const _aibo204_dsh_plugin_computer_use_computerUseArchive_image_result$schema = z.object({
  'mediaType': z.string(),
  'data': z.string(),
})
const _aibo204_dsh_plugin_computer_use_computerUseArchive_list_result$schema = z.array(z.object({
  'id': z.string().readonly(),
  'sessionId': z.string().readonly(),
  'callId': z.string().readonly(),
  'createdAt': z.number().readonly(),
  'app': z.union([z.undefined(), z.string()]).readonly().optional(),
  'action': z.string().readonly(),
  'category': z.union([z.undefined(), z.literal("send"), z.literal("delete"), z.literal("purchase"), z.literal("upload")]).readonly().optional(),
  'succeeded': z.boolean().readonly(),
  'pinned': z.boolean().readonly(),
  'bytes': z.number().readonly(),
  'phases': z.array(z.union([z.literal("before"), z.literal("after")])).readonly(),
}))
const _aibo204_dsh_plugin_computer_use_computerUseArchive_pin_parameter_0$schema = z.string()
const _aibo204_dsh_plugin_computer_use_computerUseArchive_pin_parameter_1$schema = z.boolean()
const _aibo204_dsh_plugin_computer_use_computerUseArchive_pin_result$schema = z.object({
  'id': z.string().readonly(),
  'sessionId': z.string().readonly(),
  'callId': z.string().readonly(),
  'createdAt': z.number().readonly(),
  'app': z.union([z.undefined(), z.string()]).readonly().optional(),
  'action': z.string().readonly(),
  'category': z.union([z.undefined(), z.literal("send"), z.literal("delete"), z.literal("purchase"), z.literal("upload")]).readonly().optional(),
  'succeeded': z.boolean().readonly(),
  'pinned': z.boolean().readonly(),
  'bytes': z.number().readonly(),
  'phases': z.array(z.union([z.literal("before"), z.literal("after")])).readonly(),
})

export const TYPERT = {
  package: '@aibo204/dsh-plugin-computer-use',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@aibo204/dsh-plugin-computer-use#computerUseArchive/cleanup',
      service: 'computerUseArchiveController',
      namespace: 'computerUseArchive',
      method: 'cleanup',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@aibo204/dsh-plugin-computer-use/archive#ComputerUseArchiveCleanupResult',
        schema: _aibo204_dsh_plugin_computer_use_computerUseArchive_cleanup_result$schema,
      },
      sourceLocation: {"file":"packages/computer-use/src/archive.ts","line":342,"column":3},
    },
    {
      id: '@aibo204/dsh-plugin-computer-use#computerUseArchive/delete',
      service: 'computerUseArchiveController',
      namespace: 'computerUseArchive',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@aibo204/dsh-plugin-computer-use#computerUseArchive/delete:id',
            schema: _aibo204_dsh_plugin_computer_use_computerUseArchive_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@aibo204/dsh-plugin-computer-use#computerUseArchive/delete:result',
        schema: _aibo204_dsh_plugin_computer_use_computerUseArchive_delete_result$schema,
      },
      sourceLocation: {"file":"packages/computer-use/src/archive.ts","line":332,"column":9},
    },
    {
      id: '@aibo204/dsh-plugin-computer-use#computerUseArchive/image',
      service: 'computerUseArchiveController',
      namespace: 'computerUseArchive',
      method: 'image',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@aibo204/dsh-plugin-computer-use#computerUseArchive/image:id',
            schema: _aibo204_dsh_plugin_computer_use_computerUseArchive_image_parameter_0$schema,
          },
        },
        {
          name: 'phase',
          wire: 'phase',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@aibo204/dsh-plugin-computer-use#computerUseArchive/image:phase',
            schema: _aibo204_dsh_plugin_computer_use_computerUseArchive_image_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@aibo204/dsh-plugin-computer-use#computerUseArchive/image:result',
        schema: _aibo204_dsh_plugin_computer_use_computerUseArchive_image_result$schema,
      },
      sourceLocation: {"file":"packages/computer-use/src/archive.ts","line":312,"column":9},
    },
    {
      id: '@aibo204/dsh-plugin-computer-use#computerUseArchive/list',
      service: 'computerUseArchiveController',
      namespace: 'computerUseArchive',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@aibo204/dsh-plugin-computer-use#computerUseArchive/list:result',
        schema: _aibo204_dsh_plugin_computer_use_computerUseArchive_list_result$schema,
      },
      sourceLocation: {"file":"packages/computer-use/src/archive.ts","line":306,"column":3},
    },
    {
      id: '@aibo204/dsh-plugin-computer-use#computerUseArchive/pin',
      service: 'computerUseArchiveController',
      namespace: 'computerUseArchive',
      method: 'pin',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@aibo204/dsh-plugin-computer-use#computerUseArchive/pin:id',
            schema: _aibo204_dsh_plugin_computer_use_computerUseArchive_pin_parameter_0$schema,
          },
        },
        {
          name: 'pinned',
          wire: 'pinned',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@aibo204/dsh-plugin-computer-use#computerUseArchive/pin:pinned',
            schema: _aibo204_dsh_plugin_computer_use_computerUseArchive_pin_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@aibo204/dsh-plugin-computer-use/archive#ComputerUseArchiveRecord',
        schema: _aibo204_dsh_plugin_computer_use_computerUseArchive_pin_result$schema,
      },
      sourceLocation: {"file":"packages/computer-use/src/archive.ts","line":322,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Atomic local archive with serialized mutation and bounded retention.",
        "summary": "Atomic local archive with serialized mutation and bounded retention.",
        "tags": [],
        "jsDoc": "/** Atomic local archive with serialized mutation and bounded retention. */",
        "key": "computerUseArchive",
        "exportName": "ComputerUseArchiveService",
        "members": [
          {
            "kind": "property",
            "name": "root",
            "signature": "readonly root: string",
            "summary": "Absolute private archive root.",
            "jsDoc": "/** Absolute private archive root. */"
          },
          {
            "kind": "method",
            "name": "configure",
            "signature": "configure(settings: ComputerUseArchiveSettings): void",
            "summary": "Replace the effective retention policy after a settings commit.",
            "jsDoc": "/** Replace the effective retention policy after a settings commit. */"
          },
          {
            "kind": "method",
            "name": "policy",
            "signature": "policy(): ComputerUseArchiveSettings",
            "summary": "Read the current policy for an Agent-scoped capture decision.",
            "jsDoc": "/** Read the current policy for an Agent-scoped capture decision. */"
          },
          {
            "kind": "method",
            "name": "archive",
            "signature": "archive(input: ComputerUseArchiveInput): Promise<void>",
            "summary": "Commit one action record and enforce retention after publication.",
            "jsDoc": "/** Commit one action record and enforce retention after publication. */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "list(): Promise<ComputerUseArchiveRecord[]>",
            "summary": "List newest records first; malformed or partial directories stay invisible.",
            "jsDoc": "/** List newest records first; malformed or partial directories stay invisible. */"
          },
          {
            "kind": "method",
            "name": "image",
            "signature": "image(id: string, phase: 'before' | 'after'): Promise<{ mediaType: string; data: string }>",
            "summary": "Return one archived image as canonical base64 for an on-demand preview.",
            "jsDoc": "/** Return one archived image as canonical base64 for an on-demand preview. */"
          },
          {
            "kind": "method",
            "name": "pin",
            "signature": "pin(id: string, pinned: boolean): Promise<ComputerUseArchiveRecord>",
            "summary": "Set or clear one record's retention pin.",
            "jsDoc": "/** Set or clear one record's retention pin. */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "delete(id: string): Promise<void>",
            "summary": "Delete one archive record and its private screenshot copies.",
            "jsDoc": "/** Delete one archive record and its private screenshot copies. */"
          },
          {
            "kind": "method",
            "name": "cleanup",
            "signature": "cleanup(): Promise<ComputerUseArchiveCleanupResult>",
            "summary": "Remove expired and over-quota unpinned records.",
            "jsDoc": "/** Remove expired and over-quota unpinned records. */"
          }
        ],
        "types": [
          {
            "name": "ComputerUseArchiveCleanupResult",
            "declaration": "export interface ComputerUseArchiveCleanupResult {\n    readonly deleted: number;\n    readonly bytesFreed: number;\n    readonly remainingBytes: number;\n}"
          },
          {
            "name": "ComputerUseArchiveImage",
            "declaration": "export interface ComputerUseArchiveImage {\n    readonly phase: 'before' | 'after';\n    readonly attachment: Extract<ContentBlock, { type: 'image'; }>['attachment'];\n}"
          },
          {
            "name": "ComputerUseArchiveInput",
            "declaration": "export interface ComputerUseArchiveInput {\n    readonly agent: Agent;\n    readonly callId: string;\n    readonly app?: string;\n    readonly action: string;\n    readonly category?: 'send' | 'delete' | 'purchase' | 'upload';\n    readonly succeeded: boolean;\n    readonly images: readonly ComputerUseArchiveImage[];\n}"
          },
          {
            "name": "ComputerUseArchiveMode",
            "declaration": "export type ComputerUseArchiveMode = 'off' | 'high-risk' | 'all-control';"
          },
          {
            "name": "ComputerUseArchiveRecord",
            "declaration": "export interface ComputerUseArchiveRecord {\n    readonly id: string;\n    readonly sessionId: string;\n    readonly callId: string;\n    readonly createdAt: number;\n    readonly app?: string;\n    readonly action: string;\n    readonly category?: 'send' | 'delete' | 'purchase' | 'upload';\n    readonly succeeded: boolean;\n    readonly pinned: boolean;\n    readonly bytes: number;\n    readonly phases: readonly ('before' | 'after')[];\n}"
          },
          {
            "name": "ComputerUseArchiveSettings",
            "declaration": "export interface ComputerUseArchiveSettings {\n    archiveMode: ComputerUseArchiveMode;\n    archiveRetentionDays: number;\n    archiveMaxBytes: number;\n    archiveAutoPinHighRisk: boolean;\n}"
          }
        ]
      },
      {
        "description": "Browser Remote adapter for private archive management.",
        "summary": "Browser Remote adapter for private archive management.",
        "tags": [],
        "jsDoc": "/** Browser Remote adapter for private archive management. */",
        "key": "computerUseArchiveController",
        "exportName": "ComputerUseArchiveController",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote list(): Promise<ComputerUseArchiveRecord[]>",
            "jsDoc": "/** @returns newest archive records first. */"
          },
          {
            "kind": "method",
            "name": "image",
            "signature": "@Remote async image(id: string, phase: 'before' | 'after'): Promise<{ mediaType: string; data: string }>",
            "jsDoc": "/** @returns one image encoded for a browser data URL. */"
          },
          {
            "kind": "method",
            "name": "pin",
            "signature": "@Remote async pin(id: string, pinned: boolean): Promise<ComputerUseArchiveRecord>",
            "jsDoc": "/** @returns updated record after changing its pin. */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote async delete(id: string): Promise<void>",
            "summary": "Delete one record and its private screenshot copies.",
            "jsDoc": "/** Delete one record and its private screenshot copies. */"
          },
          {
            "kind": "method",
            "name": "cleanup",
            "signature": "@Remote cleanup(): Promise<ComputerUseArchiveCleanupResult>",
            "jsDoc": "/** @returns counts and bytes from an immediate cleanup pass. */"
          }
        ],
        "types": [
          {
            "name": "ComputerUseArchiveCleanupResult",
            "declaration": "export interface ComputerUseArchiveCleanupResult {\n    readonly deleted: number;\n    readonly bytesFreed: number;\n    readonly remainingBytes: number;\n}"
          },
          {
            "name": "ComputerUseArchiveRecord",
            "declaration": "export interface ComputerUseArchiveRecord {\n    readonly id: string;\n    readonly sessionId: string;\n    readonly callId: string;\n    readonly createdAt: number;\n    readonly app?: string;\n    readonly action: string;\n    readonly category?: 'send' | 'delete' | 'purchase' | 'upload';\n    readonly succeeded: boolean;\n    readonly pinned: boolean;\n    readonly bytes: number;\n    readonly phases: readonly ('before' | 'after')[];\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
