/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ComputerUseArchiveCleanupResult, ComputerUseArchiveRecord } from '@aibo204/dsh-plugin-computer-use/archive'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636f6d707574657255736541726368697665 {
    cleanup: () => Promise<RemoteResult<ComputerUseArchiveCleanupResult>>
    delete: (id: string) => Promise<RemoteResult<void>>
    image: (id: string, phase: 'before' | 'after') => Promise<RemoteResult<{ mediaType: string; data: string; }>>
    list: () => Promise<RemoteResult<ComputerUseArchiveRecord[]>>
    pin: (id: string, pinned: boolean) => Promise<RemoteResult<ComputerUseArchiveRecord>>
  }
  interface TypertRemoteMap {
    'computerUseArchive/cleanup': () => Promise<RemoteResult<ComputerUseArchiveCleanupResult>>
    'computerUseArchive/delete': (id: string) => Promise<RemoteResult<void>>
    'computerUseArchive/image': (id: string, phase: 'before' | 'after') => Promise<RemoteResult<{ mediaType: string; data: string; }>>
    'computerUseArchive/list': () => Promise<RemoteResult<ComputerUseArchiveRecord[]>>
    'computerUseArchive/pin': (id: string, pinned: boolean) => Promise<RemoteResult<ComputerUseArchiveRecord>>
  }
  interface TypertRemoteNamespaceMap {
    'computerUseArchive': TypertRemoteNamespace$636f6d707574657255736541726368697665
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
